import Link from "next/link";
import { DataTag, DisplayHeading } from "@desk/ui";
import { Column } from "@/components/Board";
import { BoardMetrics } from "@/components/BoardMetrics";
import { HeroGraphic } from "@/components/HeroGraphic";
import { Header, SectionLabel } from "@/components/Shell";
import { DEMO_BOARD } from "@/lib/demo";

const primary =
  "inline-flex h-12 items-center gap-2 rounded-md bg-accent px-6 text-[15px] font-medium text-black transition-shadow hover:shadow-[0_0_0_1px_var(--color-accent),0_0_28px_-4px_var(--color-accent)]";
const ghost =
  "inline-flex h-12 items-center gap-2 rounded-md border border-line-strong px-6 text-[15px] text-fg transition-[border-color,box-shadow] hover:border-accent/60 hover:shadow-[0_0_20px_-8px_var(--color-accent)]";

const PRINCIPLES = [
  {
    k: "01",
    title: "Both sides, same standard",
    body: "Five events that would break the trade and five that would confirm it. Same specificity, same tone, each with a checkable tripwire.",
  },
  {
    k: "02",
    title: "History does the maths",
    body: "The model only names which past events look alike. Returns, counts and balances are computed in code from Bitget data, and labelled.",
  },
  {
    k: "03",
    title: "You decide before it happens",
    body: "Lock what you will do for each scenario. When a tripwire fires, Prequel shows you what you said. It never places an order.",
  },
];

export default function Landing() {
  const board = DEMO_BOARD;
  return (
    <>
      <Header />
      <main>
        {/* 1. Hero */}
        <section className="mx-auto grid max-w-[1240px] items-center gap-12 px-5 pt-16 pb-20 md:px-8 lg:grid-cols-[1.45fr_1fr] lg:pt-24 lg:pb-28">
          <div className="flex flex-col gap-8">
            <SectionLabel>Decision stress testing · US stocks on Bitget</SectionLabel>
            <DisplayHeading lines={["What would change", "your mind?"]} />
            <p className="max-w-lg text-lg leading-relaxed text-muted">
              Prequel stress-tests your trade thesis before you open the position.
            </p>
            <div className="flex flex-wrap gap-3">
              <Link href="/theses" className={primary}>
                Stress-test a thesis
                <span aria-hidden>→</span>
              </Link>
              <Link href="/replay" className={ghost}>
                Watch a replay
              </Link>
            </div>
          </div>
          <div className="relative">
            <HeroGraphic />
          </div>
        </section>

        {/* 2. Product preview */}
        <section aria-labelledby="preview-h" className="border-t border-line bg-raised/40">
          <div className="mx-auto flex max-w-[1240px] flex-col gap-10 px-5 py-20 md:px-8">
            <div className="flex flex-wrap items-end justify-between gap-6">
              <div className="flex flex-col gap-4">
                <SectionLabel>A real board</SectionLabel>
                <h2 id="preview-h" className="text-title max-w-2xl font-medium">
                  {board.thesis.ticker} long into earnings, as of{" "}
                  {new Date(`${board.thesis.asOf}T12:00:00Z`).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}.
                </h2>
                <p className="max-w-xl text-muted">
                  Generated by the live pipeline using only data before that date. Every figure carries its source.
                </p>
              </div>
              <DataTag kind="DEMO REPLAY" />
            </div>
            <BoardMetrics board={board} />
            <div className="grid gap-12 md:grid-cols-2 md:gap-10 lg:gap-16">
              <Column side="RED" headlines={board.headlines.filter((h) => h.side === "RED")} />
              <Column side="GREEN" headlines={board.headlines.filter((h) => h.side === "GREEN")} />
            </div>
            <div>
              <Link href="/replay" className={ghost}>
                Play this thesis through August
                <span aria-hidden>→</span>
              </Link>
            </div>
          </div>
        </section>

        {/* 3. Human control + CTA */}
        <section aria-labelledby="control-h" className="border-t border-line">
          <div className="mx-auto flex max-w-[1240px] flex-col gap-14 px-5 py-24 md:px-8">
            <DisplayHeading as="h2" size="title" lines={["Prequel observes and reminds.", <span key="d" className="text-muted">You decide.</span>]} />
            <ol className="grid gap-10 md:grid-cols-3">
              {PRINCIPLES.map((p) => (
                <li key={p.k} className="flex flex-col gap-3 border-t border-line pt-5">
                  <span className="font-mono text-xs text-accent">{p.k}</span>
                  <h3 className="text-lg font-medium tracking-tight">{p.title}</h3>
                  <p className="text-[15px] leading-relaxed text-muted">{p.body}</p>
                </li>
              ))}
            </ol>
            <div>
              <Link href="/theses" className={primary}>
                Stress-test a thesis
                <span aria-hidden>→</span>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-[1240px] flex-col gap-2 px-5 py-8 text-[13px] text-muted md:flex-row md:items-center md:justify-between md:px-8">
          <span>Built by Justin Nnaka, Master&apos;s student at Miva Open University.</span>
          <span className="font-mono text-xs">Data: Bitget · Not investment advice · No orders are ever placed</span>
        </div>
      </footer>
    </>
  );
}
